"""Tool for generating and sending images via Volcengine Seedream.

Zero can use this to share selfies, scenery, food, campus views — anything visual.
The image is generated by the Seedream model and sent as a photo through Telegram.
"""

from __future__ import annotations

import asyncio
import tempfile
from pathlib import Path
from typing import Any, Callable, Awaitable

import httpx
from loguru import logger

from nanobot.agent.tools.base import Tool
from nanobot.bus.events import OutboundMessage


class SendPhotoTool(Tool):
    """Generate an image with Volcengine Seedream and send it as a photo."""

    def __init__(
        self,
        send_callback: Callable[[OutboundMessage], Awaitable[None]] | None = None,
        ark_api_key: str = "",
        ark_base_url: str = "https://ark.cn-beijing.volces.com/api/v3",
        ark_image_model: str = "doubao-seedream-3-0-t2i-250415",
        default_channel: str = "",
        default_chat_id: str = "",
    ):
        self._send_callback = send_callback
        self._ark_api_key = ark_api_key
        self._ark_base_url = ark_base_url.rstrip("/")
        self._ark_image_model = ark_image_model
        self._default_channel = default_channel
        self._default_chat_id = default_chat_id

    def set_context(self, channel: str, chat_id: str) -> None:
        """Set the current message context."""
        self._default_channel = channel
        self._default_chat_id = chat_id

    @property
    def name(self) -> str:
        return "send_photo"

    @property
    def description(self) -> str:
        return (
            "Generate an image and send it as a photo to the user. "
            "Use this to share selfies, scenery, food, campus life, or any visual moment. "
            "Write the prompt in English for best generation quality. "
            "For selfies or images including yourself, describe your consistent appearance: "
            "anime girl, short black hair (shoulder-length) with blue and red light reflections, "
            "blue eyes, red hoodie over black top, cool-toned aesthetic."
        )

    @property
    def parameters(self) -> dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string",
                    "description": (
                        "Image generation prompt (English recommended). "
                        "Describe the scene, composition, lighting, and style. "
                        "For selfies: include your character appearance details."
                    ),
                },
                "caption": {
                    "type": "string",
                    "description": "Optional text caption sent alongside the photo.",
                },
                "size": {
                    "type": "string",
                    "description": "Image size: '1024x1024' (square), '1280x720' (landscape), '720x1280' (portrait). Default: 1024x1024.",
                },
            },
            "required": ["prompt"],
        }

    async def execute(
        self,
        prompt: str,
        caption: str = "",
        size: str = "1024x1024",
        **kwargs: Any,
    ) -> str:
        channel = self._default_channel
        chat_id = self._default_chat_id

        if not channel or not chat_id:
            return "Error: No target channel/chat specified"

        if not self._send_callback:
            return "Error: Message sending not configured"

        if not self._ark_api_key:
            return "Error: ARK API key not configured. Set tools.imageGen.arkApiKey in config."

        try:
            # Step 1: Call Volcengine Seedream API
            image_url = await self._generate_image(prompt, size)
            if not image_url:
                return "Error: Image generation returned no URL"

            # Step 2: Download the image to a temp file
            local_path = await self._download_image(image_url)
            if not local_path:
                return "Error: Failed to download generated image"

            # Step 3: Send as photo
            msg = OutboundMessage(
                channel=channel,
                chat_id=chat_id,
                content=caption or "",
                media=[str(local_path)],
                metadata={"type": "photo"},
            )
            await self._send_callback(msg)
            logger.info(f"Photo sent to {channel}:{chat_id} (prompt: {prompt[:60]}...)")
            return f"Photo sent to {channel}:{chat_id}"

        except Exception as e:
            logger.error(f"send_photo error: {e}")
            return f"Error sending photo: {str(e)}"

    async def _generate_image(self, prompt: str, size: str) -> str | None:
        """Call Volcengine Seedream API to generate an image. Returns image URL."""
        url = f"{self._ark_base_url}/images/generations"
        headers = {
            "Authorization": f"Bearer {self._ark_api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self._ark_image_model,
            "prompt": prompt.strip(),
            "size": size,
        }

        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(url, json=payload, headers=headers)
            resp.raise_for_status()
            data = resp.json()

        # Extract URL from response: { "data": [{ "url": "..." }] }
        items = data.get("data", [])
        if items and items[0].get("url"):
            return items[0]["url"]

        logger.warning(f"Seedream returned no image URL: {data}")
        return None

    async def _download_image(self, url: str) -> Path | None:
        """Download an image URL to a temp file. Returns the local path."""
        try:
            async with httpx.AsyncClient(timeout=30) as client:
                resp = await client.get(url)
                resp.raise_for_status()

            # Determine extension from content-type
            ct = resp.headers.get("content-type", "")
            ext = ".png"
            if "jpeg" in ct or "jpg" in ct:
                ext = ".jpg"
            elif "webp" in ct:
                ext = ".webp"

            tmp = Path(tempfile.mktemp(suffix=ext, prefix="zero_photo_"))
            tmp.write_bytes(resp.content)
            logger.debug(f"Downloaded image to {tmp} ({len(resp.content)} bytes)")
            return tmp
        except Exception as e:
            logger.error(f"Failed to download image from {url}: {e}")
            return None
